networks:
  presto:
    driver: bridge
    ipam:
      config:
        - subnet:  172.19.0.0/24
          gateway: 172.19.0.1

services:
  coordinator:
    container_name: coordinator
    image: prestodb/presto:latest
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - 8080:8080
    volumes:
      - ./data:/home/data
      - ./iceberg_data:/home/iceberg_data
      - ./etc_coordinator:/opt/presto-server/etc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.19.0.4:8080"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      presto:
        ipv4_address: 172.19.0.4
  sidecar:
    container_name: sidecar
    image: public.ecr.aws/oss-presto/presto-native:0.297-centos-arm64
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 8081:8081
    volumes:
      - ./data:/home/data
      - ./iceberg_data:/home/iceberg_data
      - ./etc_sidecar:/opt/presto-server/etc
    networks:
      presto:
        ipv4_address: 172.19.0.11

  worker:
    container_name: worker
    image: public.ecr.aws/oss-presto/presto-native:0.297-centos-arm64
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 8082:8082
    volumes:
      - ./data:/home/data
      - ./iceberg_data:/home/iceberg_data
      - ./etc_worker:/opt/presto-server/etc
    networks:
      presto:
        ipv4_address: 172.19.0.12
