coordinator=false
discovery.uri=http://10.18.0.8:8080
http-server.http.port=8080
memory.heap-headroom-per-node=800MB
query.max-total-memory-per-node=3GB
query.max-memory-per-node=3GB
query.max-total-memory=6GB
query.max-memory=6GB