networks:
  presto:
    driver: bridge
    ipam:
      config:
        - subnet:  172.19.0.0/24
          gateway: 172.19.0.1

services:    
  coordinator:
    container_name: coordinator
    image: prestodb/presto:latest
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
    ports:
      - 8080:8080
    volumes:
      - /tmp/data:/home
      - ./prestissimo/coordinator/log.properties:/opt/presto-server/etc/log.properties
      - ./prestissimo/coordinator/config.properties:/opt/presto-server/etc/config.properties
      - ./prestissimo/coordinator/jvm.config:/opt/presto-server/etc/jvm.config
      - ./prestissimo/coordinator/node.properties:/opt/presto-server/etc/node.properties
      - ./prestissimo/coordinator/catalog/hive_file.properties:/opt/presto-server/etc/catalog/hive.properties
      - ./prestissimo/coordinator/catalog/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
    healthcheck:
      test: ["CMD", "curl", "-f", "http://172.19.0.4:8080"]
      interval: 5m
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      presto:
        ipv4_address: 172.19.0.4

  worker_1:
    container_name: worker_1
    image: public.ecr.aws/oss-presto/presto-native:0.289-ubuntu-arm64
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 8081:8081
    volumes:
      - /tmp/data:/home
      - ./prestissimo/coordinator/log.properties:/opt/presto-server/etc/log.properties
      - ./prestissimo/workers/config_1.properties:/opt/presto-server/etc/config.properties
      - ./prestissimo/workers/node_1.properties:/opt/presto-server/etc/node.properties
      - ./prestissimo/workers/catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties
    networks:
      presto:
        ipv4_address: 172.19.0.11

  worker_2:
    container_name: worker_2
    image: public.ecr.aws/oss-presto/presto-native:0.289-ubuntu-arm64
    platform: linux/arm64
    restart: always
    deploy:
      resources:
        limits:
          memory: 4G
    ports:
      - 8082:8082
    volumes:
      - /tmp/data:/home
      - ./prestissimo/coordinator/log.properties:/opt/presto-server/etc/log.properties
      - ./prestissimo/workers/config_2.properties:/opt/presto-server/etc/config.properties
      - ./prestissimo/workers/node_2.properties:/opt/presto-server/etc/node.properties
      - ./prestissimo/workers/catalog/hive.properties:/opt/presto-server/etc/catalog/hive.properties
    networks:
      presto:
        ipv4_address: 172.19.0.12
